name: Package usage

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm install
      - name: Create package tarball
        run: |
          export ARCHIVE_FILENAME=$(npm pack | tail -n 1)
          mv $ARCHIVE_FILENAME package.tgz
      - name: Store package tarball for later
        uses: actions/upload-artifact@v4
        with:
          name: package-output
          path: package.tgz

  esm-usage:
    name: ESM usage (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]

    needs: package
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get package tarball from package step
        uses: actions/download-artifact@v4
        with:
          name: package-output
      - name: Install and test
        run: |
          export UNPACK_DESTINATION=$(mktemp -d)
          mv package.tgz $UNPACK_DESTINATION
          cp test/module-systems/esm-test.mjs $UNPACK_DESTINATION
          cd $UNPACK_DESTINATION
          npm install package.tgz
          node esm-test.mjs
